#!/bin/bash

# This is a thin wrapper around moneta-cli that strips the Windows-style EOLs
# from the output if present. It is necessary when using moneta-cli.exe on
# Linux since shells will interpret the line-endings as part of the result.

CURDIR=$(cd $(dirname "$0"); pwd)
# Get BUILDDIR and REAL_MONETAD

# Grab the value of $REAL_MONETACLI which may be moneta-cli.exe.
. "${CURDIR}/tests-config.sh"

"${REAL_MONETACLI}" "$@" | sed 's/\r//'
